"""Models package — Pydantic schemas for all data flowing through the system."""

from .article import (
    Article,
    ArticleListResponse,
    ArticleResponse,
    CreateArticleRequest,
    Material,
)
from .intel import (
    DeepDiveListResponse,
    DeepDiveResponse,
    DeepDiveSourceItem,
    DeepDiveStatus,
    DiscoveryItem,
    EventDeepDive,
    IntelAlert,
    IntelAlertListResponse,
    IntelEvent,
    IntelEventListResponse,
    IntelEventResponse,
    RawItem,
    RawItemListResponse,
    Source,
    SourceKind,
    SourceListResponse,
    SourceResponse,
)
from .operation import (
    BatchExecuteRequest,
    BatchExecuteResponse,
    BatchOnError,
    BatchStep,
    BatchStepResult,
    OperationExecuteRequest,
    OperationExecuteResponse,
    OperationResult,
    OperationSpec,
    OperationStatus,
)
from .publish import (
    Platform,
    PublishRecord,
    PublishRecordListResponse,
    PublishRecordResponse,
    PublishStatus,
    PublishTask,
    PublishTaskListResponse,
)
from .workflow import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATES,
    IllegalTransitionError,
    WorkflowListResponse,
    WorkflowResponse,
    WorkflowSession,
    WorkflowState,
    WorkflowTransitionRequest,
)

__all__ = [
    # article
    "Article",
    "ArticleListResponse",
    "ArticleResponse",
    "CreateArticleRequest",
    "Material",
    # intel
    "DeepDiveListResponse",
    "DeepDiveResponse",
    "DeepDiveSourceItem",
    "DeepDiveStatus",
    "DiscoveryItem",
    "EventDeepDive",
    "IntelAlert",
    "IntelAlertListResponse",
    "IntelEvent",
    "IntelEventListResponse",
    "IntelEventResponse",
    "RawItem",
    "RawItemListResponse",
    "Source",
    "SourceKind",
    "SourceListResponse",
    "SourceResponse",
    # operation
    "BatchExecuteRequest",
    "BatchExecuteResponse",
    "BatchOnError",
    "BatchStep",
    "BatchStepResult",
    "OperationExecuteRequest",
    "OperationExecuteResponse",
    "OperationResult",
    "OperationSpec",
    "OperationStatus",
    # publish
    "Platform",
    "PublishRecord",
    "PublishRecordListResponse",
    "PublishRecordResponse",
    "PublishStatus",
    "PublishTask",
    "PublishTaskListResponse",
    # workflow
    "ALLOWED_TRANSITIONS",
    "TERMINAL_STATES",
    "IllegalTransitionError",
    "WorkflowListResponse",
    "WorkflowResponse",
    "WorkflowSession",
    "WorkflowState",
    "WorkflowTransitionRequest",
]
